[package]
name = "clink"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A library for maintaining type-level invariants at runtime."
repository = "https://github.com/DavePearce/Clink.rs"

[dependencies]
